"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { EmptyGuard } from "@/components/empty-guard";
import { useIncidentState } from "@/components/incident-provider";

export function ResolutionScreen() {
  const router = useRouter();
  const { completedRunbookSteps, report, toggleRunbookStep } = useIncidentState();
  const [copyState, setCopyState] = useState("");

  const copiedMessage = useMemo(() => {
    if (!report) {
      return "";
    }

    return [
      report.runbook.slackMessage.header,
      report.runbook.slackMessage.body,
      report.runbook.slackMessage.footer,
    ].join("\n");
  }, [report]);

  return (
    <EmptyGuard ready={Boolean(report)}>
      {report ? (
        <>
          <div className="page-hero">
            <h1>Resolution</h1>
            <p>
              Adapted from {report.patternMatches.matches[0]?.incidentId} resolution by{" "}
              {report.patternMatches.matches[0]?.resolvedBy}
            </p>
          </div>

          <section className="resolution-grid">
            <article className="panel card">
              <div className="panel-header">
                <h2>Executable Runbook</h2>
                <span className="badge badge-green">
                  {completedRunbookSteps.length} of {report.runbook.steps.length} done
                </span>
              </div>

              <div className="runbook-list">
                {report.runbook.steps.map((step) => {
                  const complete = completedRunbookSteps.includes(step.step);

                  return (
                    <div
                      className={`step-card ${complete ? "is-complete" : ""}`}
                      key={step.step}
                    >
                      <div className="check-row">
                        <button
                          aria-label={`Toggle step ${step.step}`}
                          className="check-button"
                          onClick={() => toggleRunbookStep(step.step)}
                          style={{
                            background: complete ? "var(--green)" : "#fff",
                            borderColor: complete ? "var(--green)" : "var(--border)",
                          }}
                          type="button"
                        />

                        <div>
                          <div className="step-heading">
                            <strong>
                              Step {step.step}: {step.title}
                            </strong>
                          </div>
                          <div className="step-command mono">{step.command}</div>
                          <div className="step-verify">Verify: {step.verify}</div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </article>

            <article className="panel card">
              <div className="panel-header">
                <h2>Stakeholder Update</h2>
                <span className="badge">#payzen-incidents</span>
              </div>

              <div className="slack-card">
                <div className="slack-meta">
                  <div className="avatar">ZS</div>
                  <div>
                    <strong>ZeroMTTR SRE</strong>
                    <div style={{ color: "var(--muted)", fontSize: 13 }}>02:15 AM</div>
                  </div>
                </div>

                <pre className="mono">{copiedMessage}</pre>

                <div className="slack-actions">
                  <button
                    className="button-secondary"
                    onClick={async () => {
                      await navigator.clipboard.writeText(copiedMessage);
                      setCopyState("Copied to clipboard.");
                      window.setTimeout(() => setCopyState(""), 2200);
                    }}
                    type="button"
                  >
                    Copy Message
                  </button>
                  <button className="button-ghost" disabled type="button">
                    Send to Slack (soon)
                  </button>
                </div>
                {copyState ? <div className="toast">{copyState}</div> : null}

                <div style={{ color: "var(--muted)", fontSize: 13 }}>
                  Auto-generated by ZeroMTTR in {report.meta.mttrSeconds} seconds
                </div>
              </div>
            </article>
          </section>

          <div className="page-actions">
            <button className="button-secondary" onClick={() => router.push("/resolved")}>
              Mark Resolved →
            </button>
          </div>
        </>
      ) : null}
    </EmptyGuard>
  );
}
